### ISSUE TITLE
What to do if partial derivatives cannot be calculated?

### ISSUE THREAD

**Issue by qikang666** [geo-ant/varpro#11]
Hello,
      I have a question, if the function is too complex to calculate the partial derivatives， how to solve it ? Thanks!

**Comment by geo-ant** [comment]
Hi,

that depends on what you mean by _too complex_. First of all, your objective function must be a linear combination of some nonlinear functions, as explained [here](https://docs.rs/varpro/). Otherwise you'll get no benefit out of using `varpro`.

So I assume you are saying your individual base functions are too complex. If it's just hard (but not impossible) to calculate the derivatives, definitely do so. Use the help of tools like [Wolfram Alpha](https://www.wolframalpha.com/).

If it's not possible to write down the analytical derivatives, e.g. because your target function is the result of a simulation, then it is usually possible to calculate _numerical_ derivatives. See e.g. [here](https://en.wikipedia.org/wiki/Finite_difference) or [here](https://en.wikipedia.org/wiki/Finite_difference_coefficient). You can then pass the numerical derivatives instead of analytical ones.

However, the way I implemented `varpro` assumes analytical derivatives, so that providing numerical derivatives will make the calculations slower and possibly less numerically stable.

Alternatively, if you really cannot provide derivatives, you might be better served with _derivative-free_ optimization algorithms. If you want to keep using Rust, check out the crates [argmin](https://crates.io/crates/argmin) or [nlopt](https://crates.io/crates/nlopt). The [nlopt docs](https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/) provide a good overview of different algorithms. For a simple (yet surprisingly powerful) derivative-free algorithm take a look at the Nelder-Mead Simplex Method. Both the crates above offer an implementation of this algorithm.

One last thing: I saw on your profile that you forked rmpfit. It looks like this gives you an LM algorithm which calculates the numerical derivatives for you. While that is not strictly derivative-free, it does mean you don't have to specify the derivatives yourself. Does that not work for you? If it does, you can give `varpro` with numerical derivatives a try and see how it performs. You would have to write your own function for calculating the numerical derivatives,though.

**Comment by qikang666** [comment]
Thanks a lot !
