### ISSUE TITLE
How to implement a model with 100+ partial derivatives

### ISSUE THREAD

**Issue by JorisDeRidder** [geo-ant/varpro#28]
Hi, 
the model I would like to fit is a slope plus a linear combination of (well separated) Gaussian functions. This is exactly where VarPro shines. However, in my use case, the sum consists of 100+ Gaussian functions, each having a location and a width as non-linear parameters. Do you have any suggestions on how to implement this in VarPro? 

The problem I'm facing is that coding each of the 200+ partial derivatives separately is a bit cumbersome. Moreover, the exact number of Gaussian functions may only be known at run time. Is there a shorter way to specify them?  In principle the partial derivative of e.g. the position of the `n`-th Gaussian is easy to compute IF you can pass the number `n`, but I don't see if this can be done with the current version.

**Comment by geo-ant** [comment]
Hi, I only now read this issue, let me make sure I understand your application.

First, when you say the number of Gaussians is only known at runtime, do you mean that at runtime it will be decided whether the model consists of M or N Gaussians _before_ fitting the data? Or is the number of Gaussians something you want the fitting algorithm to decide for you? The first case should be pretty straightforward, in the second case there is no direct way to include that into varpro. You'd have to do some additional work on model selection, but varpro does help you by providing fit uncertainties.

Secondly: aargh, this answer was getting pretty long :) I definitely believe your function should be pretty straightforward to translate into a varpro model. But I need some additional info on what is making your life hard. If you look at the separable model builder as it's written in the documentation it might seem hard to add 200 functions in there, but it's really not. You could e.g. use the  thing in a for loop like so: (sorry bad pseudocode, but you get the idea)

Let's say the model parameters are sigma_1,..., sigma_N

```
let mut builder  = SeparableModelBuilder::<f64>::new(&[ all the parameters of the model for all N gaussians]);

for i in 1..N {
   builder  = builder
.function([parameters for gaussian i], function)
.partial_deriv(format!("sigma_{}",i),partial_deriv);
}

let model = builder.build().unwrap();
```
You might want to use a closure (lambda) to parametrize the gaussian at index `i` on some constants that only depend on `i`.

Are you comfortable with posting the expression? If so I can give more targeted advice. And maybe I did not understand the problem. If you are not comfortable posting your problem online I can give you my email and I can try to help you privately, where you can share as little or as much info as you want. I also believe that using the model builder might be an okay first step but especially for your problem you'll get a lot of benefits if you use the more expert interface that let's you implement the `SeparableNonlinearModel` trait for your problem yourself. See [the docs here](https://docs.rs/varpro/0.8.0/varpro/model/trait.SeparableNonlinearModel.html). Also contains an example of how to manually implement it. I can also help you there :)

Finally I cannot promise that varpro will be able to solve your problem. If the basis functions become collinear it will get into trouble, but so will other least squares solvers. I actually used the solving backend (SVD rather than QR) with the most robustness against singularities but it is something to consider. That depends on whether the Gaussians are likely to become collinear which depends on their exact functional form and what parts of the Gaussians are actually variable. Oh and also I am pretty sure I assumed that the problem was overdetermined so if you have more parameters than data you might run into trouble. But maybe not :). And your application seems super interesting, so I am willing to help and see if varpro can help you solve your problem.

EDIT: I just reread your comment and you said that the Gaussians are well separated so that's great.
EDIT2: I just realized you also gave the function you want to fit... reading comprehension skills F. If my ramblings helped you let me know. Otherwise I'll try and post some code how to implement that function.

**Comment by geo-ant** [comment]
Hey again @JorisDeRidder , 

here is a complete example (a binary) that uses the builder interface in varpro 0.8.0 to create a model of this underlying form:

$$f(x) = a\cdot x+b +\sum_n c_n\cdot N(\mu_n,\sigma_n )$$

```rust
use nalgebra::DVector;
use std::f32::consts::FRAC_2_SQRT_PI;
use varpro::model::builder::{SeparableModelBuilder, SeparableModelBuilderProxyWithDerivatives};

fn main() {
    // the number of gaussians can be set at runtime
    let n_gaussians = 5;
    let x = DVector::from_vec(vec![1., 2., 3.]);

    // we create the list of parameters at runtime using only the number of gaussians in the model
    let builder = SeparableModelBuilder::<f64>::new(mu_sigma_vec_for_n_gaussians(n_gaussians))
        // slope a of the linear function. Contains no nonlinear parameters
        .invariant_function(|x| x.clone())
        // intercept b of the linear function. No nonlinear params
        .invariant_function(|x| DVector::from_element(x.nrows(), 1.))
        // the support on which the data was measured (the x coordinate)
        .independent_variable(x)
        // your educated guess for the initial parameters. Only the nonlinear parameters!
        .initial_parameters(initial_params_mu_sigma(n_gaussians));

    assert!(n_gaussians >= 1);

    // we have to add the first gaussian outside the for loop.
    // this is a problem in my API design. I tried being clever here. Note to self: fix!
    let mut builder = builder
        .function(&["mu1", "sigma1"], gaussian)
        .partial_deriv("mu1", dgaussian_dmu)
        .partial_deriv("sigma1", dgaussian_dsigma);

    // now we can add all the other gaussians programmatically.
    // gaussian at index n will depend on nonlinear parameters mu[n] and sigma[n]
    for n in 2..=n_gaussians {
        builder = builder
            .function(&[format!("mu{n}"), format!("sigma{n}")], gaussian)
            .partial_deriv(format!("mu{n}"), dgaussian_dmu)
            .partial_deriv(format!("sigma{n}"), dgaussian_dsigma);
    }

    let model = builder.build().unwrap();
    println!("finished setting up model");

    // now for the fitting part. You should be able to use the code as listed on crates.io
}

/// returns a vector with contents "mu1","sigma1",...,"mu[n]","sigma[n]"
fn mu_sigma_vec_for_n_gaussians(n_gaussians: usize) -> Vec<String> {
    let mut mu_sigma_vec = Vec::with_capacity(2 * n_gaussians);
    for n in 1..=n_gaussians {
        mu_sigma_vec.push(format!("mu{n}"));
        mu_sigma_vec.push(format!("sigma{n}"));
    }
    mu_sigma_vec
}

/// some dummy initial parameters for the list of mu1,sigma1,mu2,sigma2,...
fn initial_params_mu_sigma(n_gaussians: usize) -> Vec<f64> {
    let mut initial = Vec::with_capacity(2 * n_gaussians);
    for n in 1..=n_gaussians {
        //initial mu[n] is n
        initial.push(n as f64);
        // initial sigma[n] is 1
        initial.push(1.);
    }
    initial
}

/// the gaussian function itself
fn gaussian(xvec: &DVector<f64>, mu: f64, sigma: f64) -> DVector<f64> {
    // todo, pls recheck. I might have mistyped something
    const FRAC_SQRT_2PI: f64 =
        std::f64::consts::FRAC_2_SQRT_PI * 0.5 * std::f64::consts::FRAC_1_SQRT_2;
    xvec.map(|x| FRAC_SQRT_2PI / sigma * (-0.5 * (x - mu) * (x - mu) / (sigma * sigma)).exp())
}

/// the partial derivative of a gaussian wrt sigma
fn dgaussian_dsigma(xvec: &DVector<f64>, mu: f64, sigma: f64) -> DVector<f64> {
    // this is left as an exercise for the reader :)
    // see the code above for inspiration
    todo!()
}

/// the partial derivative of a gaussian wrt mu
fn dgaussian_dmu(xvec: &DVector<f64>, mu: f64, sigma: f64) -> DVector<f64> {
    todo!()
}
```

That should do the trick. The first two LINEAR parameters of the model are the slope and intercept of the linear function, respectively. Then come the amplitudes of the gaussians. The nonlinear parameters are $\mu_1$, $\sigma_1$ ,..., $\mu_N$ , $\sigma_N$, with N being the number of Gaussians.

 Please give this a shot and let me know if you run into problems. If you find the performance is lacking, we can explore using the advanced interface, but it'll require some going back and forth on optimizations.

Note also that I used `f64` here. You might not need that kind of precision, but this is something that you can iterate on once you got the thing going at all.

**Comment by JorisDeRidder** [comment]
Hi @geo-ant, this is exactly what I was looking for! Many thanks!

**Comment by geo-ant** [comment]
> Hi @geo-ant, this is exactly what I was looking for! Many thanks!

@JorisDeRidder wonderful. Will you let me know if it worked for your usecase? I'd be very interested just out of curiosity.

**Comment by geo-ant** [comment]
Merged into main by https://github.com/geo-ant/varpro/pull/33, which is part of the 0.9.0 release. Now there is no need anymore to add the first function outside the loop. All the invocations to add functions and partial derivatives can be performed inside the loop.

**Comment by geo-ant** [comment]
Hey @JorisDeRidder, I was wondering if you were able to fit the sum-of-Gaussians with varpro. It's pure curiosity. Even if varpro wasn't able to do it, I'd be interested to know what went wrong.

**Comment by JorisDeRidder** [comment]
Hi @geo-ant, on some datasets it worked well, for other it did not work well. That doesn't mean there is anything wrong with the library, though. I will make a more extensive report, but I'm a bit swamped with work at the moment. I'll come back later to it.

**Comment by geo-ant** [comment]
Hey @JorisDeRidder, thanks, I did not mean to rush you, I was just curious. When you mentioned the application I wondered how varpro would fare. Not having to explicitly consider the linear parameters is surely a plus. However, beyond that it's still general purpose least squares fitting and the problem seems pretty badly behaved, e.g. because the Gaussian peaks can become collinear easily during the process (if they aren't far apart). Also varpro does not take explicit advantage of the fact that in your case all the base functions have the same form and that no two base functions share parameters. I'm definitely interested to hear more of what worked and what did not. When you have time, no rush.
